spring.application.name=sb-ecom

#Db connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#Enabling Flyway
spring.flyway.enabled=true

#Flyway, if the database already has tables but you don?t see your history table,create one and start tracking from here.
spring.flyway.baseline-on-migrate=true

#Call the current state of the database version 1.
spring.flyway.baseline-version=1

#Add a human-readable note explaining why this baseline exists.
spring.flyway.baseline-description=baseline-exsisting-schema

#Now this update will be changing to validate instead of the update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.org.flywaydb=INFO

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.flywaydb=DEBUG


#ImagesBucket
supabase.url=${SUPABASE_URL}
supabase.serviceKey=${SUPABASE_SECRET_KEY}
supabase.bucket=${SUPABASE_BUCKET:product-images}

#JWT-Issuer
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://ehgvmynjpyuvqiylzhzx.supabase.co/auth/v1

#This will change.
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.cookieName =${COOKIE_NAME}


# Test user creds:seller

userName="newuser4"
password="Secret9"

# Test user creds2: Admin,Seller

userName3="newuser3"
password3="Secret9"

# Low stock scheduler
alerts.stock.low-threshold=${LOW_STOCK_THRESHOLD}
alerts.stock.cron=${LOW_STOCK_CRON}

# Telegram bot alerts
alerts.telegram.enabled=${TELEGRAM_ALERT_ENABLED}
alerts.telegram.bot-token=${TELEGRAM_BOT_TOKEN}
alerts.telegram.chat-id=${TELEGRAM_CHAT_ID}
