spring.application.name=sb-ecom
spring.config.import=optional:classpath:application-secrets.properties

#Db connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO


#ImagesBucket
supabase.url=${SUPABASE_URL}
supabase.serviceKey=${SUPABASE_SECRET_KEY}
supabase.bucket=${SUPABASE_BUCKET:product-images}



