# ===== Database secrets =====
DB_URL=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
DB_USERNAME=postgres.ehgvmynjpyuvqiylzhzx
DB_PASSWORD=Buyology@123

# ===== Supabase secrets =====
SUPABASE_URL=https://ehgvmynjpyuvqiylzhzx.supabase.co
SUPABASE_SECRET_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZ3ZteW5qcHl1dnFpeWx6aHp4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzg0MDY3NSwiZXhwIjoyMDc5NDE2Njc1fQ.K2SHQ4wm-Oz3JGnEBXZpTRBcuAO3Mfw1BtSLYi_yF6U
SUPABASE_BUCKET=product-images