
-- Create the role and user table

CREATE TABLE roles(
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL,
    CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);



-- creat users table

CREATE TABLE users(
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name VARCHAR(20) NOT NULL,
        email VARCHAR(50) NOT NULL,
        password VARCHAR(120) NOT NULL,
        CONSTRAINT uq_users_email UNIQUE (email),
        CONSTRAINT uq_users_user_name UNIQUE (user_name)
);

-- NO NEED TO CREATE THE INDEX SEPARATELY CONSTRAINT WILL AUTOMATICALLY CREATE THE INDEX.


-- CREAT A JOIN TABLE FOR THE USERS AND ROLES RELATION --
--  user_role join table (Many-to-Many relationship) --

CREATE TABLE user_role (
        user_id BIGINT NOT NULL,
        role_id INTEGER NOT NULL,
    -- prevents duplicates: same user can't get same role twice
        PRIMARY KEY (user_id, role_id),
        FOREIGN KEY (user_id) REFERENCES users(user_id),
        FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

--
