-- add the foreign key column to products

ALTER TABLE product
ADD COLUMN seller_id BIGINT NOT NULL;


-- Add foreign key constraint

ALTER TABLE product
ADD CONSTRAINT fk_products_seller
FOREIGN KEY (seller_id)
REFERENCES users(user_id);


-- CREATE THE ADDRESS TABLE!
CREATE TABLE addresses(
                      address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      street VARCHAR(20) NOT NULL,
                      building_name VARCHAR(50) NOT NULL,
                      city VARCHAR(120) NOT NULL,
                      state VARCHAR(20) NOT NULL,
                      country VARCHAR(50) NOT NULL,
                      zip_code VARCHAR(120) NOT NULL
);


-- CREAT A JOIN TABLE FOR THE USERS AND ADDRESS RELATION --
--  user_address join table (Many-to-Many relationship) --

CREATE TABLE user_address(
    user_id BIGINT NOT NULL,
    address_id BIGINT NOT NULL,

    CONSTRAINT pk_user_address PRIMARY KEY (user_id, address_id),
    CONSTRAINT fk_user_address_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_address_address FOREIGN KEY (address_id) REFERENCES addresses(address_id)
)