CREATE TABLE cart
(
    cart_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT           NOT NULL,
    total_price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id),
    CONSTRAINT uq_cart_user UNIQUE (user_id)
);



CREATE TABLE cart_item
(
    cart_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id       BIGINT           NOT NULL,
    product_id    BIGINT           NOT NULL,
    quantity      INTEGER          NOT NULL,
    discount      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    product_price DOUBLE PRECISION NOT NULL,

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES cart (cart_id),

    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id)
            REFERENCES product (product_id),

-- Prevent duplicate product rows within the same cart
    CONSTRAINT uq_cart_item_cart_product UNIQUE (cart_id, product_id)
);

CREATE INDEX idx_cart_item_cart_id ON cart_item (cart_id);
CREATE INDEX idx_cart_item_product_id ON cart_item (product_id);
CREATE INDEX idx_product_category_id ON product(category_id);
